POST http://localhost:8080/access
Content-Type: application/json

{
    "email": "change2@mail.com",
    "password": "test1"
}

PUT http://localhost:8080/email
Content-Type: application/json

{
    "id": "0002",
    "session": "df5cbf4c-cc53-11ee-bd13-d05f643363e0",
    "email": "change2@mail.com"
}
